### PR TITLE
Fix for...in loops for old browsers

### LINKED ISSUE #199: Don't use for...in at all for old browsers compatibility
Every use of `for...in` in this lib make it unusable with IE11:

3a522928-ebda-11e6-8a9d-ef88d5c1339e

Should be fixed:
- [opening_hours.js#L4263](https://github.com/opening-hours/opening_hours.js/blob/01c3dd02927765d632fcc74375c83e7aa837faad/opening_hours.js#L4263)
- [opening_hours.js#L4315](https://github.com/opening-hours/opening_hours.js/blob/01c3dd02927765d632fcc74375c83e7aa837faad/opening_hours.js#L4315)

@ypid I can make a PR, what's your preference?

### 1. Classic for loop with idx increment
```js
for (var selector_ind=0; selector_ind<selector_elements.length; selector_ind++) {
   // ...
}
```

### 2. Object.hasOwnProperty assertion
```js
for (var selector_ind in selector_elements) {
    if (selector_elements.hasOwnProperty(selector_ind)) {
        // ...
    }
}
```

### PR DESCRIPTION
**Pull request by shouze**
Fixes #199

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -337,7 +337,7 @@
                 /* Optimal order of selectors for checking. */
                 var selector_elements = ['year', 'holiday', 'month', 'monthday', 'week', 'weekday'];
                 for (var selector_ind in selector_elements) {
-                    if (selectors[selector_elements[selector_ind]].length > 0) {
+                    if (selector_elements.hasOwnProperty(selector_ind) && selectors[selector_elements[selector_ind]].length > 0) {
```
Comment (ypid) [inline index.js]: Ever since the [goto fail vulnerability](https://www.dwheeler.com/essays/apple-goto-fail.html) I try to use if with braces. Since the project does not have advanced unit testing and static code analysis yet, I would prefer that. Feel fee to add a linting tool to check for that. I have not really looked into eslint and others yet but I will.

Comment (shouze) [inline index.js]: Ok fine I'm pretty agree, I was just trying to comply with existing code formatting but yes it's not consistent everywhere.

So... in this case I suggest to make a PR first to put in place ESLint & fix existing code formatting, then rebase & push again on this PR, WDYT?

Comment (shouze) [inline index.js]: @ypid about formatting... in fact there's probably 2 options:
- eslint (I'm used to use it with [this kind of .eslintrc](https://gist.github.com/shouze/aab54d5f54030cafe091174b18fccb1c) which extends the airbnb one which is pretty complete
- [prettier](https://github.com/prettier/prettier) which is more a bet but very promising I guess, especially as it won't be as complicated as eslint by design for the sake.

Comment (ypid) [inline index.js]: There is also [xo](https://github.com/sindresorhus/xo) which I wanted to take a closer look at. I guess either one or even multiple combined should do the job just fine. Still better than none of the above and only uglifyjs with its warnings.

> So... in this case I suggest to make a PR first to put in place ESLint & fix existing code formatting, then rebase & push again on this PR, WDYT?

SGTM :wink:

Comment (shouze) [inline index.js]: Ok will have a try with prettier and eventually fallback to `xo` if prettier is not mature enough. `xo` would be cool as prettier without the eslint mess so would be a very good fallback candidate.

**Comment by shouze** [comment]
@ypid ok in fact... looks like if you polyfill correctly Internet Explorer the opening_hours lib won't crash anymore because of `for...in`, can you confirm me @MikaFima?

If yes I guess we can close this issue. BTW will look soon to make a PR about automated code formating (xo/eslint/prettier).

**Comment by shouze** [comment]
If yes... I guess we can also add a note in the README on how to correctly polyfill under IE with the great https://polyfill.io/

**Comment by ypid** [comment]
I stumped across this issue yesterday and did a quick check. Seems for-in is not the for-in that developers might know from other languages. https://stackoverflow.com/questions/9329446/for-each-over-an-array-in-javascript/9329476#9329476

So seems a regular for loop or the use of function programming elements like map should be preferred to solve #199. What do you think? I would not like to rely on https://polyfill.io/

**Comment by simon04** [comment]
Why not use [`Array.prototype.forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) and [`Object.keys`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) for iterating over arrays and objects, respectively? In my opinion, this makes the code clearer.

A different approach would be to use [`for...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) from ES6, and use a transpiler such as [buble](https://buble.surge.sh/guide/).

**Comment by MikaFima** [comment]
I've breakpointed this piece of code, and at some point [selector_ind](https://github.com/opening-hours/opening_hours.js/pull/207/files#diff-168726dbe96b3ce427e7fedce31bb0bcR339) become `includes`, which is a prototype method on arrays. So the @shouze workaround, or we can thing about (forEach)[https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/forEach] IE9+ compatible

**Comment by shouze** [comment]
@simon04 yup you make a point on the fact that we want to patch the code... or if we decide to transpile it with buble/babel/whatEverTranspiler. If we transpile, it as implications on the build chain of the project but it's easier to modernize the lib & write it in es6 whilst distribute it transpiled to a level of support we decide.

I suggest we can patch first then release as it's probably fast to do while the transpilation needs some tooling & discussions. So I can use forEach & keys ATM yes.

**Comment by ypid** [comment]
> I suggest we can patch first then release as it's probably fast to do while the transpilation needs some tooling & discussions. So I can use forEach & keys ATM yes.

Sounds good to me. I also like the idea of using transpiler to support legacy JS engines/browsers. Tooling (rollup) is now needed anyway so adding a transpiler does not really change much.

**Comment by ypid** [comment]
Any updates? Also note that I worked a bit on the core in the mean time. A rebase will be needed.

**Comment by shouze** [comment]
@ypid ok done, I've separated into a dedicated commit for loops that I consider a bit tricky.

I see no other good option to improve them ATM and I want to have your feedback ;)

File: index.js [hunk 2]
```diff
@@ -404,15 +404,19 @@ export default function(value, nominatim_object, optional_conf_parm) {
...
+        var exact_match = false;
 
-        for (var osm_key in osm_tag_defaults) {
+        Object.keys(osm_tag_defaults).forEach(function (osm_key) {
+            if (exact_match === true) {
+                return;
+            }
             if (key === osm_key) { // Exact match.
                 regex_key = osm_key;
-                break;
```
Comment (ypid) [inline index.js]: Seems you can just `return` from here or am I missing something? I just tried it and it works.

Comment (shouze) [inline index.js]: Yes but the behavior is inconsistent between browsers... especialy old browsers... like IE11 for example ^^

a return in a `forEach` stop the loop only on some modern browsers like chrome or firefox.

capture d ecran 2017-03-21 a 09 46 21

Comment (shouze) [inline index.js]: BTW I'm not very proud of the `tricky point` commit but as we know, will be a greater project to rewrite the lib in es6 for example and transpile it, this way relying on either babel/traceur (not sure to include buble as it don't (intentionnaly) transpile too deep maybe)

Comment (shouze) [inline index.js]: So of course @simon04 @ypid I can squash commits if we intend to merge without changes.

Comment (ypid) [inline index.js]: > BTW I'm not very proud of the tricky point commit but as we know, will be a greater project to rewrite the lib in es6 for example and transpile it, this way relying on either babel/traceur (not sure to include buble as it don't (intentionnaly) transpile too deep maybe)

Ah, I knew I missed something :smile: Sure, the transpile option would be preferred. You can do this when you want as discussed above. If not, maybe add an comment to explain why this was needed, otherwise, it might get refactored since all tests are passing even with the old code. You might want to add an integration test to ensure that compatibility stays and does not get broken again.

> So of course @simon04 @ypid I can squash commits if we intend to merge without changes.

Yes, I guess you could squash the last commit.

Comment (shouze) [inline index.js]: > Ah, I knew I missed something 😄 Sure, the transpile option would be preferred. You can do this when you want as discussed above. If not, maybe add an comment to explain why this was needed, otherwise, it might get refactored since all tests are passing even with the old code. You might want to add an integration test to ensure that compatibility stays and does not get broken again.

Ok I add a comment and I squash. Unfortunately for the integration test... it depends on the js vm (especially the IE one).

About the ES6 rewrite & transpilation I will give a try soon after this PR merge.

Comment (ypid) [inline index.js]: Sounds good to me, thanks. I will merge this later today then.

File: index.js [hunk 3]
```diff
@@ -404,15 +404,21 @@ export default function(value, nominatim_object, optional_conf_parm) {
...
+                // We can't just return here as some old browsers
```
Comment (shouze) [inline index.js]: Added this comment to avoid to break with some future refactor and until we don't drive browser support/deprecation through a transpiler.

**Comment by shouze** [comment]
@ypid ok so maybe it's time to make a new tagged release? So much changes since last release 😉

**Comment by ypid** [comment]
Almost there :wink: https://github.com/opening-hours/opening_hours.js/milestone/11
